import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { ChevronLeft, ChevronRight, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PageIntro, ReadyCTA } from '@/components/travel/site';
import { gallery } from '@/data/content';
export const Route=createFileRoute('/gallery')({head:()=>({meta:[{title:"Галерея Египта — Pharaoh's Path"},{name:'description',content:'Пирамиды, Нил, древние храмы и Красное море в фотографиях наших маршрутов.'},{property:'og:title',content:"Галерея Египта — Pharaoh's Path"},{property:'og:description',content:'Откройте Египет в фотографиях наших путешествий.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:Gallery});
const categories=['Все','Пирамиды','Каир','Луксор','Нил','Красное море','Пустыня'];
function Gallery(){const [category,setCategory]=useState('Все');const [selected,setSelected]=useState<number|null>(null);const visible=gallery.filter(g=>category==='Все'||g.category===category);useEffect(()=>{if(selected===null)return;function key(e:KeyboardEvent){if(e.key==='Escape')setSelected(null);if(e.key==='ArrowRight')setSelected(i=>i===null?null:(i+1)%visible.length);if(e.key==='ArrowLeft')setSelected(i=>i===null?null:(i+visible.length-1)%visible.length)}document.addEventListener('keydown',key);document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=''}},[selected,visible.length]);let touch=0;return <div className="subpage"><PageIntro eyebrow="Визуальный дневник" title="Моменты Египта" text="Есть места, которые невозможно объяснить словами. Их можно только почувствовать."/><div className="container"><div className="filter-bar">{categories.map(x=><Button key={x} variant="outline" className={`filter-pill ${category===x?'selected':''}`} onClick={()=>{setCategory(x);setSelected(null)}}>{x}</Button>)}</div><div className="gallery-grid">{visible.map((item,i)=><Button key={`${item.title}-${i}`} variant="ghost" className="gallery-tile" onClick={()=>setSelected(i)} aria-label={`Открыть: ${item.title}`}><img src={item.image} alt={item.title} loading="lazy"/><span>{item.title}</span></Button>)}</div></div>{selected!==null&&<div className="lightbox" role="dialog" aria-modal="true" aria-label="Просмотр фотографии" onTouchStart={e=>touch=e.touches[0].clientX} onTouchEnd={e=>{const dx=e.changedTouches[0].clientX-touch;if(Math.abs(dx)>45)setSelected((selected+(dx<0?1:visible.length-1))%visible.length)}}><Button variant="ghost" size="icon" className="lightbox-close" aria-label="Закрыть" onClick={()=>setSelected(null)}><X/></Button><Button variant="ghost" size="icon" className="lightbox-prev" aria-label="Предыдущая фотография" onClick={()=>setSelected((selected+visible.length-1)%visible.length)}><ChevronLeft/></Button><img src={visible[selected].image} alt={visible[selected].title}/><Button variant="ghost" size="icon" className="lightbox-next" aria-label="Следующая фотография" onClick={()=>setSelected((selected+1)%visible.length)}><ChevronRight/></Button><div className="lightbox-caption">{visible[selected].title} · {selected+1} / {visible.length}</div></div>}<ReadyCTA/></div>}
