import { Link, useRouterState } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { ArrowRight, ArrowUpRight, ChevronLeft, ChevronRight, Instagram, Menu, Star, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { faq, formatPrice, testimonials, tours, type Tour } from '@/data/content';

export const nav = [{to:'/',label:'Главная'},{to:'/tours',label:'Туры'},{to:'/about',label:'О нас'},{to:'/gallery',label:'Галерея'},{to:'/blog',label:'Блог'},{to:'/contacts',label:'Контакты'}] as const;
export function Brand({light=false}:{light?:boolean}) { return <Link to="/" className={`brand ${light?'brand-light':''}`} aria-label="Pharaoh's Path — главная"><svg viewBox="0 0 44 44" fill="none" aria-hidden="true"><path d="M4 35 22 5l18 30H4Z" stroke="currentColor" strokeWidth="1.6"/><path d="M22 5v30M12 35l10-17 10 17" stroke="currentColor" strokeWidth="1.1"/><path d="M4 39h36" stroke="currentColor" strokeWidth="1.6"/></svg><span>Pharaoh's <em>Path</em></span></Link> }
export function Navbar(){ const path=useRouterState({select:s=>s.location.pathname}); const [scrolled,setScrolled]=useState(false); const [open,setOpen]=useState(false); useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>48);onScroll();window.addEventListener('scroll',onScroll);return()=>window.removeEventListener('scroll',onScroll)},[]); useEffect(()=>setOpen(false),[path]); useEffect(()=>{document.body.style.overflow=open?'hidden':'';return()=>{document.body.style.overflow=''}},[open]); const overlay=path==='/'&&!scrolled&&!open;return <header className={`site-header ${overlay?'header-overlay':''} ${open?'header-open':''}`}><div className="container nav-inner"><Brand light={overlay||open}/><nav className="desktop-nav" aria-label="Главное меню">{nav.map(item=><Link key={item.to} to={item.to} activeOptions={{exact:true}} className="nav-link" activeProps={{className:'nav-link active'}}>{item.label}</Link>)}</nav><Button asChild className="nav-book desktop-book"><Link to="/booking">Забронировать <ArrowUpRight size={16}/></Link></Button><Button variant="ghost" size="icon" className="mobile-menu-button" aria-label={open?'Закрыть меню':'Открыть меню'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button></div>{open&&<nav className="mobile-nav" aria-label="Мобильное меню">{nav.map((item,i)=><Link key={item.to} to={item.to}><small>0{i+1}</small>{item.label}<ArrowUpRight size={20}/></Link>)}<Button asChild className="wide"><Link to="/booking">Забронировать путешествие <ArrowRight size={17}/></Link></Button></nav>}</header>}
export function Footer(){return <footer className="footer"><div className="container footer-top"><div><Brand light/><p>Египет, который остаётся с вами.<br/>Индивидуальные путешествия с вниманием к каждой детали.</p></div><div><h3>Навигация</h3>{nav.map(x=><Link key={x.to} to={x.to}>{x.label}</Link>)}</div><div><h3>Направления</h3>{['Каир','Гиза','Луксор','Асуан','Шарм-эль-Шейх','Хургада'].map(x=><Link key={x} to="/tours">{x}</Link>)}</div><div><h3>Контакты</h3><span>По вопросам путешествий</span><a href="mailto:hello@pharaohspath.ru">hello@pharaohspath.ru</a><span>Мы на связи каждый день</span><Link to="/contacts">Написать нам <ArrowUpRight size={15}/></Link></div></div><div className="container footer-bottom"><span>© 2026 Pharaoh's Path. Все права защищены.</span><span>Путешествия с душой и смыслом</span></div></footer>}
export function SectionHeading({eyebrow,title,aside}:{eyebrow:string,title:string,aside?:React.ReactNode}){return <div className="section-heading"><div><div className="eyebrow"><span/> {eyebrow}</div><h2>{title}</h2></div>{aside&&<div className="heading-aside">{aside}</div>}</div>}
export function TourCard({tour}:{tour:Tour}){return <article className="tour-card"><Link to="/tours/$id" params={{id:tour.id}} className="tour-image"><img src={tour.image} alt={tour.title} loading="lazy"/><span className="image-badge">{tour.type}</span></Link><div className="tour-content"><div className="tour-topline"><span>{tour.days} {tour.days===5?'дней':'дней'} · {tour.region}</span><span className="rating"><Star size={14} fill="currentColor"/> {tour.rating}</span></div><h3><Link to="/tours/$id" params={{id:tour.id}}>{tour.title}</Link></h3><p>{tour.description}</p><div className="tour-bottom"><div><small>от</small><strong>{formatPrice(tour.price)}</strong><small> / чел.</small></div><Button variant="outline" asChild size="icon" aria-label={`Подробнее: ${tour.title}`}><Link to="/tours/$id" params={{id:tour.id}}><ArrowUpRight size={18}/></Link></Button></div></div></article>}
export function TourGrid({items=tours}:{items?:Tour[]}){return <div className="tour-grid">{items.map(t=><TourCard key={t.id} tour={t}/>)}</div>}
export function FAQ(){return <section className="section faq-section"><div className="container faq-layout"><div><div className="eyebrow"><span/> Вопросы и ответы</div><h2 className="display-heading">Перед путешествием</h2><p className="muted-copy">Мы собрали ответы на вопросы, которые помогут вам увереннее планировать поездку.</p><Button asChild variant="outline" className="mt-6"><Link to="/contacts">Задать свой вопрос <ArrowUpRight size={16}/></Link></Button></div><Accordion type="single" collapsible className="faq-list">{faq.map(([q,a],i)=><AccordionItem value={`item-${i}`} key={q}><AccordionTrigger className="faq-question">{q}</AccordionTrigger><AccordionContent className="faq-answer">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>}
export function Testimonials(){const [index,setIndex]=useState(0);const [pause,setPause]=useState(false);useEffect(()=>{if(pause)return;const t=setInterval(()=>setIndex(i=>(i+1)%testimonials.length),6500);return()=>clearInterval(t)},[pause]);const item=testimonials[index] ?? testimonials[0];let touch=0;return <section className="section testimonials" onMouseEnter={()=>setPause(true)} onMouseLeave={()=>setPause(false)} onTouchStart={e=>{touch=e.touches[0].clientX;setPause(true)}} onTouchEnd={e=>{const dx=e.changedTouches[0].clientX-touch;if(Math.abs(dx)>45)setIndex(i=>(i+(dx<0?1:testimonials.length-1))%testimonials.length)}}><div className="container"><SectionHeading eyebrow="Впечатления" title="Истории наших путешественников"/><div className="testimonial-body"><div className="quote-mark">“</div><div><div className="stars" aria-label="5 из 5 звёзд">★★★★★</div><blockquote>{item?.text}</blockquote><div className="testimonial-meta"><div className="avatar">{item?.name.slice(0,1)}</div><div><strong>{item?.name}</strong><span>{item?.city} · {item?.tour}</span></div></div></div></div><div className="slider-controls"><div className="dots">{testimonials.map((_,i)=><Button key={i} variant="ghost" size="icon" className={i===index?'dot active':'dot'} aria-label={`Показать отзыв ${i+1}`} onClick={()=>{setIndex(i);setPause(true)}}><span/></Button>)}</div><div className="arrow-controls"><Button variant="outline" size="icon" aria-label="Предыдущий отзыв" onClick={()=>{setIndex((index+testimonials.length-1)%testimonials.length);setPause(true)}}><ChevronLeft/></Button><Button variant="outline" size="icon" aria-label="Следующий отзыв" onClick={()=>{setIndex((index+1)%testimonials.length);setPause(true)}}><ChevronRight/></Button></div></div></div></section>}
export function PageIntro({eyebrow,title,text}:{eyebrow:string,title:string,text:string}){return <div className="page-intro container"><div className="eyebrow"><span/> {eyebrow}</div><h1>{title}</h1><p>{text}</p></div>}
export function ReadyCTA(){return <section className="ready"><div className="container ready-inner"><div><div className="eyebrow"><span/> Следующий шаг</div><h2>Ваш Египет начинается здесь</h2><p>Расскажите, о каком путешествии вы мечтаете. Остальное мы продумаем вместе.</p></div><Button asChild className="button-gold"><Link to="/booking">Подобрать путешествие <ArrowUpRight size={18}/></Link></Button></div></section>}
