/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as BlogIdRouteImport } from './routes/blog.$id'
import { Route as ToursIndexRouteImport } from './routes/tours.index'
import { Route as ToursIdRouteImport } from './routes/tours.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BlogRoute,
} as any)
const ToursIndexRoute = ToursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToursRoute,
} as any)
const ToursIdRoute = ToursIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ToursRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/tours': typeof ToursRouteWithChildren
  '/blog/$id': typeof BlogIdRoute
  '/tours/$id': typeof ToursIdRoute
  '/tours/': typeof ToursIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/blog/$id': typeof BlogIdRoute
  '/tours/$id': typeof ToursIdRoute
  '/tours': typeof ToursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/tours': typeof ToursRouteWithChildren
  '/blog/$id': typeof BlogIdRoute
  '/tours/$id': typeof ToursIdRoute
  '/tours/': typeof ToursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/gallery'
    | '/tours'
    | '/blog/$id'
    | '/tours/$id'
    | '/tours/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog' | '/gallery' | '/blog/$id' | '/tours/$id' | '/tours'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/gallery'
    | '/tours'
    | '/blog/$id'
    | '/tours/$id'
    | '/tours/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  ToursRoute: typeof ToursRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof BlogRoute
    }
    '/tours/': {
      id: '/tours/'
      path: '/'
      fullPath: '/tours/'
      preLoaderRoute: typeof ToursIndexRouteImport
      parentRoute: typeof ToursRoute
    }
    '/tours/$id': {
      id: '/tours/$id'
      path: '/$id'
      fullPath: '/tours/$id'
      preLoaderRoute: typeof ToursIdRouteImport
      parentRoute: typeof ToursRoute
    }
  }
}

interface BlogRouteChildren {
  BlogIdRoute: typeof BlogIdRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogIdRoute: BlogIdRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ToursRouteChildren {
  ToursIdRoute: typeof ToursIdRoute
  ToursIndexRoute: typeof ToursIndexRoute
}

const ToursRouteChildren: ToursRouteChildren = {
  ToursIdRoute: ToursIdRoute,
  ToursIndexRoute: ToursIndexRoute,
}

const ToursRouteWithChildren = ToursRoute._addFileChildren(ToursRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  GalleryRoute: GalleryRoute,
  ToursRoute: ToursRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
